### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/pd-geohub-migration#2]
@aescherling given that this repository is open source (👍 👍 💯 ) we should add a license. 

Our guidance at ITA has had us defaulting to the Apache license. See [Sewer](https://github.com/CityOfLosAngeles/sewer/blob/master/LICENSE) for an example. You are free to use whatever license works best for your office, though.

**Comment by aescherling** [comment]
@hunterowens thanks for the heads up! I've added an Apache license. I'll keep this in mind for other repositories as well.
